USE [MYTRA]
GO
/****** Object:  Table [dbo].[ANNOUNCE]    Script Date: 11/27/2022 6:26:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ANNOUNCE](
	[ID] [uniqueidentifier] NOT NULL,
	[TITLE] [nvarchar](250) NULL,
	[REGISTER DATE] [datetime] NULL,
	[UPDATE DATE] [datetime] NULL,
	[IS ACTIVE] [bit] NULL,
 CONSTRAINT [PK_ANNOUNCE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ANNOUNCE DETAIL]    Script Date: 11/27/2022 6:26:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ANNOUNCE DETAIL](
	[ANNOUNCE] [uniqueidentifier] NULL,
	[ID] [uniqueidentifier] NOT NULL,
	[DETAIL] [nvarchar](750) NULL,
	[REGISTER DATE] [datetime] NULL,
	[UPDATE DATE] [datetime] NULL,
	[IS ACTIVE] [bit] NULL,
 CONSTRAINT [PK_ANNOUNCE DETAIL] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CATEGORY]    Script Date: 11/27/2022 6:26:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CATEGORY](
	[ID] [uniqueidentifier] NOT NULL,
	[REGISTER DATE] [datetime] NULL,
	[UPDATE DATE] [datetime] NULL,
	[IS ACTIVE] [bit] NULL,
 CONSTRAINT [PK_CATEGORY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONTENT]    Script Date: 11/27/2022 6:26:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTENT](
	[CONTENT TYPE] [uniqueidentifier] NULL,
	[CATEGORY] [uniqueidentifier] NULL,
	[ID] [uniqueidentifier] NOT NULL,
	[REGISTER DATE] [datetime] NULL,
	[UPDATE DATE] [datetime] NULL,
	[IS ACTIVE] [bit] NULL,
 CONSTRAINT [PK_CONTENT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONTENT COMMENT]    Script Date: 11/27/2022 6:26:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTENT COMMENT](
	[CONTENT] [uniqueidentifier] NULL,
	[USER] [uniqueidentifier] NULL,
	[ID] [uniqueidentifier] NOT NULL,
	[REGISTER DATE] [datetime] NULL,
	[UPDATE DATE] [datetime] NULL,
	[IS ACTIVE] [bit] NULL,
 CONSTRAINT [PK_CONTENT COMMENT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONTENT DETAIL]    Script Date: 11/27/2022 6:26:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTENT DETAIL](
	[ID] [uniqueidentifier] NOT NULL,
	[REGISTER DATE] [datetime] NULL,
	[UPDATE DATE] [datetime] NULL,
	[IS ACTIVE] [bit] NULL,
 CONSTRAINT [PK_CONTENT DETAIL] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONTENT LIKE]    Script Date: 11/27/2022 6:26:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTENT LIKE](
	[CONTENT] [uniqueidentifier] NULL,
	[USER] [uniqueidentifier] NULL,
	[ID] [uniqueidentifier] NOT NULL,
	[REGISTER DATE] [datetime] NULL,
	[UPDATE DATE] [datetime] NULL,
	[IS ACTIVE] [bit] NULL,
 CONSTRAINT [PK_CONTENT LIKE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONTENT PICTURE]    Script Date: 11/27/2022 6:26:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTENT PICTURE](
	[CONTENT] [uniqueidentifier] NULL,
	[ID] [uniqueidentifier] NOT NULL,
	[REGISTER DATE] [datetime] NULL,
	[UPDATE DATE] [datetime] NULL,
	[IS ACTIVE] [bit] NULL,
 CONSTRAINT [PK_CONTENT PICTURE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONTENT SETTINGS]    Script Date: 11/27/2022 6:26:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTENT SETTINGS](
	[ID] [uniqueidentifier] NOT NULL,
	[REGISTER DATE] [datetime] NULL,
	[UPDATE DATE] [datetime] NULL,
	[IS ACTIVE] [bit] NULL,
 CONSTRAINT [PK_CONTENT SETTINGS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONTENT TYPE]    Script Date: 11/27/2022 6:26:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTENT TYPE](
	[ID] [uniqueidentifier] NOT NULL,
	[REGISTER DATE] [datetime] NULL,
	[UPDATE DATE] [datetime] NULL,
	[IS ACTIVE] [bit] NULL,
 CONSTRAINT [PK_CONTENT TYPE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MANAGEMENT]    Script Date: 11/27/2022 6:26:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MANAGEMENT](
	[ID] [uniqueidentifier] NOT NULL,
	[USERNAME] [nvarchar](50) NULL,
	[EMAIL] [varchar](50) NULL,
	[PASSWORD] [nvarchar](50) NULL,
	[REFRESH TOKEN] [nvarchar](50) NULL,
	[REFRESH VALID DATE] [datetime] NULL,
	[REGISTER DATE] [datetime] NULL,
	[UPDATE DATE] [datetime] NULL,
	[IS ACTIVE] [bit] NULL,
 CONSTRAINT [PK_MANAGEMENT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MANAGEMENT CONTACT]    Script Date: 11/27/2022 6:26:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MANAGEMENT CONTACT](
	[MANAGEMENT] [uniqueidentifier] NULL,
	[ID] [uniqueidentifier] NOT NULL,
	[REGISTER DATE] [datetime] NULL,
	[UPDATE DATE] [datetime] NULL,
	[IS ACTIVE] [bit] NULL,
 CONSTRAINT [PK_MANAGEMENT CONTACT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MANAGEMENT DETAIL]    Script Date: 11/27/2022 6:26:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MANAGEMENT DETAIL](
	[ID] [uniqueidentifier] NOT NULL,
	[REGISTER DATE] [datetime] NULL,
	[UPDATE DATE] [datetime] NULL,
	[IS ACTIVE] [bit] NULL,
 CONSTRAINT [PK_MANAGEMENT DETAIL] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MANAGEMENT SETTINGS]    Script Date: 11/27/2022 6:26:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MANAGEMENT SETTINGS](
	[ID] [uniqueidentifier] NOT NULL,
	[REGISTER DATE] [datetime] NULL,
	[UPDATE DATE] [datetime] NULL,
	[IS ACTIVE] [bit] NULL,
 CONSTRAINT [PK_MANAGEMENT SETTINGS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PERMISSION]    Script Date: 11/27/2022 6:26:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERMISSION](
	[ID] [uniqueidentifier] NOT NULL,
	[REGISTER DATE] [datetime] NULL,
	[UPDATE DATE] [datetime] NULL,
	[IS ACTIVE] [bit] NULL,
 CONSTRAINT [PK_PERMISSION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PERMISSION DETAIL]    Script Date: 11/27/2022 6:26:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERMISSION DETAIL](
	[PERMISSION] [uniqueidentifier] NULL,
	[ID] [uniqueidentifier] NOT NULL,
	[REGISTER DATE] [datetime] NULL,
	[UPDATE DATE] [datetime] NULL,
	[IS ACTIVE] [bit] NULL,
 CONSTRAINT [PK_PERMISSION DETAIL] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SURVEY]    Script Date: 11/27/2022 6:26:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SURVEY](
	[ID] [uniqueidentifier] NOT NULL,
	[REGISTER DATE] [datetime] NULL,
	[UPDATE DATE] [datetime] NULL,
	[IS ACTIVE] [bit] NULL,
 CONSTRAINT [PK_SURVEY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USER]    Script Date: 11/27/2022 6:26:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER](
	[ID] [uniqueidentifier] NOT NULL,
	[USERNAME] [nvarchar](50) NULL,
	[EMAIL] [varchar](50) NULL,
	[PASSWORD] [nvarchar](50) NULL,
	[REFRESH TOKEN] [nvarchar](50) NULL,
	[REFRESH VALID DATE] [datetime] NULL,
	[REGISTER DATE] [datetime] NULL,
	[UPDATE DATE] [datetime] NULL,
	[IS ACTIVE] [bit] NULL,
 CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USER CONTACT]    Script Date: 11/27/2022 6:26:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER CONTACT](
	[USER] [uniqueidentifier] NULL,
	[ID] [uniqueidentifier] NOT NULL,
	[REGISTER DATE] [datetime] NULL,
	[UPDATE DATE] [datetime] NULL,
	[IS ACTIVE] [bit] NULL,
 CONSTRAINT [PK_USER CONTACT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USER DETAIL]    Script Date: 11/27/2022 6:26:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER DETAIL](
	[ID] [uniqueidentifier] NOT NULL,
	[REGISTER DATE] [datetime] NULL,
	[UPDATE DATE] [datetime] NULL,
	[IS ACTIVE] [bit] NULL,
 CONSTRAINT [PK_USER DETAIL] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USER EMAIL]    Script Date: 11/27/2022 6:26:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER EMAIL](
	[USER] [uniqueidentifier] NULL,
	[ID] [uniqueidentifier] NOT NULL,
	[REGISTER DATE] [datetime] NULL,
	[UPDATE DATE] [datetime] NULL,
	[IS ACTIVE] [bit] NULL,
 CONSTRAINT [PK_USER EMAIL] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USER SETTINGS]    Script Date: 11/27/2022 6:26:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER SETTINGS](
	[ID] [uniqueidentifier] NOT NULL,
	[REGISTER DATE] [datetime] NULL,
	[UPDATE DATE] [datetime] NULL,
	[IS ACTIVE] [bit] NULL,
 CONSTRAINT [PK_USER SETTINGS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ANNOUNCE DETAIL]  WITH CHECK ADD  CONSTRAINT [FK_ANNOUNCE DETAIL_ANNOUNCE] FOREIGN KEY([ANNOUNCE])
REFERENCES [dbo].[ANNOUNCE] ([ID])
GO
ALTER TABLE [dbo].[ANNOUNCE DETAIL] CHECK CONSTRAINT [FK_ANNOUNCE DETAIL_ANNOUNCE]
GO
ALTER TABLE [dbo].[CONTENT]  WITH CHECK ADD  CONSTRAINT [FK_CONTENT_CATEGORY] FOREIGN KEY([CATEGORY])
REFERENCES [dbo].[CATEGORY] ([ID])
GO
ALTER TABLE [dbo].[CONTENT] CHECK CONSTRAINT [FK_CONTENT_CATEGORY]
GO
ALTER TABLE [dbo].[CONTENT]  WITH CHECK ADD  CONSTRAINT [FK_CONTENT_CONTENT TYPE] FOREIGN KEY([CONTENT TYPE])
REFERENCES [dbo].[CONTENT TYPE] ([ID])
GO
ALTER TABLE [dbo].[CONTENT] CHECK CONSTRAINT [FK_CONTENT_CONTENT TYPE]
GO
ALTER TABLE [dbo].[CONTENT COMMENT]  WITH CHECK ADD  CONSTRAINT [FK_CONTENT COMMENT_CONTENT] FOREIGN KEY([CONTENT])
REFERENCES [dbo].[CONTENT] ([ID])
GO
ALTER TABLE [dbo].[CONTENT COMMENT] CHECK CONSTRAINT [FK_CONTENT COMMENT_CONTENT]
GO
ALTER TABLE [dbo].[CONTENT COMMENT]  WITH CHECK ADD  CONSTRAINT [FK_CONTENT COMMENT_USER] FOREIGN KEY([USER])
REFERENCES [dbo].[USER] ([ID])
GO
ALTER TABLE [dbo].[CONTENT COMMENT] CHECK CONSTRAINT [FK_CONTENT COMMENT_USER]
GO
ALTER TABLE [dbo].[CONTENT LIKE]  WITH CHECK ADD  CONSTRAINT [FK_CONTENT LIKE_CONTENT] FOREIGN KEY([CONTENT])
REFERENCES [dbo].[CONTENT] ([ID])
GO
ALTER TABLE [dbo].[CONTENT LIKE] CHECK CONSTRAINT [FK_CONTENT LIKE_CONTENT]
GO
ALTER TABLE [dbo].[CONTENT LIKE]  WITH CHECK ADD  CONSTRAINT [FK_CONTENT LIKE_USER] FOREIGN KEY([USER])
REFERENCES [dbo].[USER] ([ID])
GO
ALTER TABLE [dbo].[CONTENT LIKE] CHECK CONSTRAINT [FK_CONTENT LIKE_USER]
GO
ALTER TABLE [dbo].[CONTENT PICTURE]  WITH CHECK ADD  CONSTRAINT [FK_CONTENT PICTURE_CONTENT] FOREIGN KEY([CONTENT])
REFERENCES [dbo].[CONTENT] ([ID])
GO
ALTER TABLE [dbo].[CONTENT PICTURE] CHECK CONSTRAINT [FK_CONTENT PICTURE_CONTENT]
GO
ALTER TABLE [dbo].[MANAGEMENT CONTACT]  WITH CHECK ADD  CONSTRAINT [FK_MANAGEMENT CONTACT_MANAGEMENT] FOREIGN KEY([MANAGEMENT])
REFERENCES [dbo].[MANAGEMENT] ([ID])
GO
ALTER TABLE [dbo].[MANAGEMENT CONTACT] CHECK CONSTRAINT [FK_MANAGEMENT CONTACT_MANAGEMENT]
GO
ALTER TABLE [dbo].[MANAGEMENT DETAIL]  WITH CHECK ADD  CONSTRAINT [FK_MANAGEMENT DETAIL_MANAGEMENT] FOREIGN KEY([ID])
REFERENCES [dbo].[MANAGEMENT] ([ID])
GO
ALTER TABLE [dbo].[MANAGEMENT DETAIL] CHECK CONSTRAINT [FK_MANAGEMENT DETAIL_MANAGEMENT]
GO
ALTER TABLE [dbo].[MANAGEMENT SETTINGS]  WITH CHECK ADD  CONSTRAINT [FK_MANAGEMENT SETTINGS_MANAGEMENT] FOREIGN KEY([ID])
REFERENCES [dbo].[MANAGEMENT] ([ID])
GO
ALTER TABLE [dbo].[MANAGEMENT SETTINGS] CHECK CONSTRAINT [FK_MANAGEMENT SETTINGS_MANAGEMENT]
GO
ALTER TABLE [dbo].[PERMISSION DETAIL]  WITH CHECK ADD  CONSTRAINT [FK_PERMISSION DETAIL_PERMISSION] FOREIGN KEY([PERMISSION])
REFERENCES [dbo].[PERMISSION] ([ID])
GO
ALTER TABLE [dbo].[PERMISSION DETAIL] CHECK CONSTRAINT [FK_PERMISSION DETAIL_PERMISSION]
GO
ALTER TABLE [dbo].[USER CONTACT]  WITH CHECK ADD  CONSTRAINT [FK_USER CONTACT_USER] FOREIGN KEY([USER])
REFERENCES [dbo].[USER] ([ID])
GO
ALTER TABLE [dbo].[USER CONTACT] CHECK CONSTRAINT [FK_USER CONTACT_USER]
GO
ALTER TABLE [dbo].[USER DETAIL]  WITH CHECK ADD  CONSTRAINT [FK_USER DETAIL_USER] FOREIGN KEY([ID])
REFERENCES [dbo].[USER] ([ID])
GO
ALTER TABLE [dbo].[USER DETAIL] CHECK CONSTRAINT [FK_USER DETAIL_USER]
GO
ALTER TABLE [dbo].[USER EMAIL]  WITH CHECK ADD  CONSTRAINT [FK_USER EMAIL_USER] FOREIGN KEY([USER])
REFERENCES [dbo].[USER] ([ID])
GO
ALTER TABLE [dbo].[USER EMAIL] CHECK CONSTRAINT [FK_USER EMAIL_USER]
GO
ALTER TABLE [dbo].[USER SETTINGS]  WITH CHECK ADD  CONSTRAINT [FK_USER SETTINGS_USER] FOREIGN KEY([ID])
REFERENCES [dbo].[USER] ([ID])
GO
ALTER TABLE [dbo].[USER SETTINGS] CHECK CONSTRAINT [FK_USER SETTINGS_USER]
GO
