// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mytra.DataAccess;

#nullable disable

namespace Mytra.DataAccess.Migrations
{
    [DbContext(typeof(MytraContext))]
    [Migration("20250902055054_dytyryt")]
    partial class dytyryt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mytra.Core.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(6);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnOrder(3);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.ToTable("Candidate", (string)null);
                });

            modelBuilder.Entity("Mytra.Core.CandidateAuthentication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("CandidateAuthentication", (string)null);
                });

            modelBuilder.Entity("Mytra.Core.CandidateCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("CandidateCertificate", (string)null);
                });

            modelBuilder.Entity("Mytra.Core.CandidateContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("CandidateContact", (string)null);
                });

            modelBuilder.Entity("Mytra.Core.CandidateDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("CandidateDetail", (string)null);
                });

            modelBuilder.Entity("Mytra.Core.CandidateEducation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("CandidateEducation", (string)null);
                });

            modelBuilder.Entity("Mytra.Core.CandidateExperience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("CandidateExperience", (string)null);
                });

            modelBuilder.Entity("Mytra.Core.CandidateLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("CandidateLanguage", (string)null);
                });

            modelBuilder.Entity("Mytra.Core.CandidatePhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("CandidatePhoto", (string)null);
                });

            modelBuilder.Entity("Mytra.Core.CandidateReferance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("CandidateReferance", (string)null);
                });

            modelBuilder.Entity("Mytra.Core.CandidateSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("CandidateSettings", (string)null);
                });

            modelBuilder.Entity("Mytra.Core.CandidateSkills", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("CandidateSkills", (string)null);
                });

            modelBuilder.Entity("Mytra.Core.College", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("College", (string)null);
                });

            modelBuilder.Entity("Mytra.Core.Institution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("Institution", (string)null);
                });

            modelBuilder.Entity("Mytra.Core.JobPosting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("JobPosting", (string)null);
                });

            modelBuilder.Entity("Mytra.Core.JobPostingApply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("JobPostingApply", (string)null);
                });

            modelBuilder.Entity("Mytra.Core.JobPostingDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("JobPostingDetail", (string)null);
                });

            modelBuilder.Entity("Mytra.Core.JobPostingVisit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("JobPostingVisit", (string)null);
                });

            modelBuilder.Entity("Mytra.Core.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("Language", (string)null);
                });

            modelBuilder.Entity("Mytra.Core.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("Manager", (string)null);
                });

            modelBuilder.Entity("Mytra.Core.ManagerAuthentication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("ManagerAuthentication", (string)null);
                });

            modelBuilder.Entity("Mytra.Core.ManagerDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("ManagerDetail", (string)null);
                });

            modelBuilder.Entity("Mytra.Core.ManagerSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("ManagerSettings", (string)null);
                });

            modelBuilder.Entity("Mytra.Core.Skills", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("Skills", (string)null);
                });

            modelBuilder.Entity("Mytra.Core.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Mytra.Core.UserAuthentication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("UserAuthentication", (string)null);
                });

            modelBuilder.Entity("Mytra.Core.UserDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("UserDetail", (string)null);
                });

            modelBuilder.Entity("Mytra.Core.UserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("UserSettings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
